[holomapping]
files = [
    "*/**",
    "!php-config/Git.config.d/",
    "!sencha-workspace/ext/**/rtl/**",
    "!sencha-workspace/ext/**/test/**",
    "!sencha-workspace/ext/classic/theme-aria/**",
    "!sencha-workspace/ext/classic/theme-classic/**",
    "!sencha-workspace/ext/classic/theme-classic-sandbox/**",
    "!sencha-workspace/ext/classic/theme-gray/**",
    "!sencha-workspace/ext/modern/theme-*/**"
]
before = "*"
